# Parameters for the SMS Spam Classification Project

# Data splitting parameters
split:
  test_size: 0.25
  random_state: 42

# Feature engineering parameters
feature_engineering:
  max_features: 900  # Maximum number of features for TF-IDF
  ngram_range: [1, 2]  # Unigrams and bigrams
  min_df: 2  # Minimum document frequency

# Model parameters
# model:
#   type: logistic_regression  # Options: logistic_regression, naive_bayes, random_forest, svm
#   C: 1.0
#   max_iter: 1000

# Alternative model configurations (uncomment to use)
# Naive Bayes
# model:
#   type: naive_bayes
#   alpha: 1.0

# Random Forest
# model:
#   type: random_forest
#   n_estimators: 300
#   max_depth: null

#SVM
# model:
#   type: svm
#   C: 1.0
#   kernel: rbf
